# GET ALL USERS
GET http://localhost:5000/users
###

# GET A SINGLE USER
GET  http://localhost:5000/users/1
###

# REGISTER A USER 
POST http://localhost:5000/register
Content-Type: application/json

{
  "name": "Mary Reed",
  "email": "maryreed@example.com",
  "password": "password112"
}
###

# LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "maryreed@example.com",
  "password": "password112"
}
###

# GET ALL BOOKINGS
GET http://localhost:5000/bookings
###

# GET A SINGLE BOOKING
GET  http://localhost:5000/bookings/1
###

# GET A USER'S BOOKINGS
GET http://localhost:5000/users/1/bookings
###

# GET ALL LISTINGS
GET http://localhost:5000/listings
###

